# Cirrus CI configuration for FreeBSD 14.2
freebsd_instance:
  image_family: freebsd-14-2
  cpu: 2
  memory: 4G

# Main build task
build_task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: "Build packages for FreeBSD:14:amd64"
  alias: data

  # Cache poudriere components
  poudriere_cache:
    folder: /usr/local/gershwin-build   
    fingerprint: "global"

  # Install dependencies
  install_script:
    - pkg update
    - pkg install -y git
    - pkg install -y poudriere
  
  # Build steps
  build_script:
    - make ports
  
  # Publish packages
  publish_script:
    - mkdir -p "$(pwd)/FreeBSD:14:amd64/All"
    - mkdir -p "$(pwd)/FreeBSD:14:amd64/Latest"
    - cp /usr/local/gershwin-build/poudriere/data/packages/gershwin_base-gershwin_ports/.latest/All/*.pkg "$(pwd)/FreeBSD:14:amd64/All/"
    - cp -r /usr/local/gershwin-build/poudriere/data/packages/gershwin_base-gershwin_ports/.latest/Latest/* "$(pwd)/FreeBSD:14:amd64/Latest/" || true
    - cd "$(pwd)/FreeBSD:14:amd64" && pkg repo .
  
  # Upload artifacts
  packages_artifacts:
    path: "./FreeBSD:14:amd64/**/*"
