# Cirrus CI configuration for FreeBSD 14.3
freebsd_instance:
  image_family: freebsd-14-3
  cpu: 8
  memory: 16G

# Main build task
build_task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: "Build packages for FreeBSD:14:amd64"
  alias: data

  # Install dependencies
  install_script:
    - pkg update
    - pkg install -y git
    - pkg install -y poudriere
    - pkg install -y tree

  # Update ports
  update_ports_script:
    - make update
  
  # Build steps
  build_script:
    - make ports

  # Publish packages
  publish_script:
    - mkdir -p "$(pwd)/FreeBSD:14:amd64/All"
    - mkdir -p "$(pwd)/FreeBSD:14:amd64/Latest"
    - cp /usr/local/gershwin-build/poudriere/data/packages/gershwin_base-gershwin_ports/.latest/All/*.pkg "$(pwd)/FreeBSD:14:amd64/All/"
    - cp -r /usr/local/gershwin-build/poudriere/data/packages/gershwin_base-gershwin_ports/.latest/Latest/* "$(pwd)/FreeBSD:14:amd64/Latest/" || true
    - cd "$(pwd)/FreeBSD:14:amd64" && pkg repo .
    - tree -h -D -C -H -./ --houtro=/dev/null -T 'Gershwin packages for FreeBSD' ./ > ./index.html
  
  # Upload artifacts
  packages_artifacts:
    path: "./FreeBSD:14:amd64/**/*"
