# Cirrus CI configuration for FreeBSD 14.2
freebsd_instance:
  image_family: freebsd-14-2
  cpu: 2
  memory: 4G

# Main build task
build_task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: "Build packages"
  
  # Install dependencies
  install_script:
    - pkg update
    - pkg install -y git
    - pkg install -y poudriere
  
  # Build steps
  build_script:
    - make ports
  
  # Publish packages
  publish_script:
    - mkdir -p /tmp/artifacts/FreeBSD:14:amd64/
    - cp -R /usr/local/gershwin-build/poudriere/data/packages/gershwin_base-gershwin_ports/ /tmp/artifacts/
  
  # Upload artifacts
  packages_artifacts:
    path: "/tmp/artifacts/**"
