PORTNAME=	gershwin-rik-theme
DISTVERSION=       202507271315
CATEGORIES=	x11-themes gnustep

MAINTAINER=	jpm820@proton.me
COMMENT=	Gershwin Rik theme
WWW=		https://github.com/gershwin-desktop/gershwin-rik-theme

LICENSE=	GPLv2

USES=		gershwin
USE_GERSHWIN=	back build gui

USE_GITHUB=	yes
GH_ACCOUNT=	gershwin-desktop
GH_TAGNAME= 2ac17e008300e680af04e0e497c11c23668dc52c

.include <bsd.port.mk>
