PORTNAME=	gershwin-rik-theme
DISTVERSION=       202507261941
CATEGORIES=	x11-themes gnustep

MAINTAINER=	jpm820@proton.me
COMMENT=	Gershwin Rik theme
WWW=		https://github.com/gershwin-desktop/gershwin-rik-theme

LICENSE=	GPLv2

USES=		gershwin
USE_GERSHWIN=	back build gui

USE_GITHUB=	yes
GH_ACCOUNT=	gershwin-desktop
GH_TAGNAME= 1ff2993d8de98d35ae7553004586697866d2a160

.include <bsd.port.mk>
