PORTNAME=	apps-gorm
DISTVERSION=       202507271315
CATEGORIES=	devel gnustep
PKGNAMEPREFIX=	gershwin-

MAINTAINER=	jpm820@proton.me
COMMENT=	Graphical Object Relationship Modeller
WWW=		http://www.gnustep.org/experience/Gorm.html

LICENSE=	GPLv3

USES=		gershwin
CONFLICTS=	gorm
USE_GERSHWIN=	back build gui

USE_GITHUB=	yes
GH_ACCOUNT=	gnustep
GH_TAGNAME= b58b9e0b19c1e449c688c3c6780c69d620f1318c

MAKE_ARGS+=     GNUSTEP_INSTALLATION_DOMAIN=LOCAL

.include <bsd.port.mk>
