PORTNAME=	gershwin-textedit
DISTVERSION=       202507271325
CATEGORIES=	deskutils gnustep

MAINTAINER=	jpm820@proton.me
COMMENT=	Gershwin TextEdit for GNUstep
WWW=		https://github.com/gershwin-desktop/gershwin-textedit

LICENSE=	MIT

USES=		gershwin
USE_GERSHWIN=	back build

USE_GITHUB=	yes
GH_ACCOUNT=	gershwin-desktop
GH_TAGNAME= 10df828f8810e8414e319e9f657f1eed12545044

.include <bsd.port.mk>
