PORTNAME=	gershwin-systempreferences
DISTVERSION=       202507271315
CATEGORIES=	deskutils gnustep

MAINTAINER=	jpm820@proton.me
COMMENT=	System Preferences application for Gershwin
WWW=		https://github.com/gershwin-desktop/gershwin-systempreferences

LICENSE=	GPLv2

USES=		gershwin
CONFLICTS=	systempreferences
USE_GERSHWIN=	back build
USE_LDCONFIG=	${GNUSTEP_SYSTEM_LIBRARIES}

USE_GITHUB=	yes
GH_ACCOUNT=	gershwin-desktop
GH_TAGNAME= 666397f0cd105f9b0c9d8735bcc7d162a714bd51

.include <bsd.port.mk>
