PORTNAME=	gershwin-systempreferences
DISTVERSION=       202509271954
CATEGORIES=	deskutils gnustep

MAINTAINER=	joe.maloney@icloud.com
COMMENT=	System Preferences application for Gershwin
WWW=		https://github.com/gershwin-desktop/gershwin-systempreferences

LICENSE=	GPLv2

USES=		gershwin
CONFLICTS=	systempreferences
USE_GERSHWIN=	back build
USE_LDCONFIG=	${GNUSTEP_SYSTEM_LIBRARIES}

USE_GITHUB=	yes
GH_ACCOUNT=	gershwin-desktop
GH_TAGNAME= eb5430620bf1865d888a7f2a62c938f11829c565

.include <bsd.port.mk>
